// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Eb9J4pvVSfrW_AibrkgZ_F_cb1xPu-k',
    appId: '1:255407023596:android:5c16fe4bbf5c895b738cc9',
    messagingSenderId: '255407023596',
    projectId: 'troski-57a6a',
    storageBucket: 'troski-57a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpEqt6ztRlMkKXnmi3zmMRPagXTJoj9w',
    appId: '1:255407023596:ios:2aa3d8d99d009e03738cc9',
    messagingSenderId: '255407023596',
    projectId: 'troski-57a6a',
    storageBucket: 'troski-57a6a.appspot.com',
    androidClientId: '255407023596-vs4ctg70g8n97vnkrptddo3sl6bpmepm.apps.googleusercontent.com',
    iosClientId: '255407023596-5hk2sj1ibsdqfqk8g0jhq88b4ikgbh1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.troskiTest',
  );
}
